CREATE TABLE C##EBAY.TBL_ARTICULO (
    ID_ARTICULO            NUMBER NOT NULL,
    ID_CATEGORIA           NUMBER NOT NULL,
    ID_ESTADO_ARTICULO     NUMBER NOT NULL,
    ID_PUNTUACION_ARTICULO NUMBER NOT NULL,
    NOMBRE                 VARCHAR2(100) NOT NULL,
    TITULO                 VARCHAR2(100),
    DESCRIPCION            VARCHAR2(255),
    MARCA                  VARCHAR2(100) NOT NULL,
    MODELO                 VARCHAR2(100) NOT NULL,
    IMAGEN                 BLOB NOT NULL
);

ALTER TABLE C##EBAY.TBL_ARTICULO ADD CONSTRAINT ARTICULO_PK PRIMARY KEY (ID_ARTICULO);

CREATE TABLE C##EBAY.TBL_CARRITOS (
    ID_CARRITO NUMBER NOT NULL,
    ID_VENTA   NUMBER NOT NULL,
    CANTIDAD   NUMBER NOT NULL
);

ALTER TABLE C##EBAY.TBL_CARRITOS ADD CONSTRAINT CARRITO_PK PRIMARY KEY (ID_CARRITO, ID_VENTA);

CREATE TABLE C##EBAY.TBL_CATEGORIA (
    ID_CATEGORIA NUMBER NOT NULL,
    NOMBRE       VARCHAR2(100) NOT NULL,
    DESCRIPCION  VARCHAR2(255)
);

ALTER TABLE C##EBAY.TBL_CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA);

CREATE TABLE C##EBAY.TBL_DIRECCIONES (
    ID_DIRECCION          NUMBER NOT NULL,
    ID_DIRECCION_SUPERIOR NUMBER,
    ID_TIPO_LUGAR         NUMBER NOT NULL,
    NOMBRE                VARCHAR2(100) NOT NULL,
    LONGITUD              VARCHAR2(100),
    LATITUD               VARCHAR2(100)
);

ALTER TABLE C##EBAY.TBL_DIRECCIONES ADD CONSTRAINT DIRECCIONES_PK PRIMARY KEY (ID_DIRECCION);

CREATE TABLE C##EBAY.TBL_DIRECCIONES_ENVIO (
    ID_USUARIO   NUMBER NOT NULL,
    ID_DIRECCION NUMBER NOT NULL,
    PRIORIDAD    VARCHAR2(1) NOT NULL,
    LONGITUD     VARCHAR2(100),
    LATITUD      VARCHAR2(100)
);

ALTER TABLE C##EBAY.TBL_DIRECCIONES_ENVIO ADD CONSTRAINT DIR_ENVIO_PK PRIMARY KEY (ID_USUARIO, ID_DIRECCION);

CREATE TABLE C##EBAY.TBL_DIRECCIONES_RECIBO (
    ID_USUARIO   NUMBER NOT NULL,
    ID_DIRECCION NUMBER NOT NULL,
    PRIORIDAD    VARCHAR2(1) NOT NULL,
    LONGITUD     VARCHAR2(100),
    LATITUD      VARCHAR2(100)
);

ALTER TABLE C##EBAY.TBL_DIRECCIONES_RECIBO ADD CONSTRAINT DIR_RECIBO_PK PRIMARY KEY (ID_USUARIO, ID_DIRECCION);

CREATE TABLE C##EBAY.TBL_ESTADO_ARTICULO (
    ID_ESTADO_ARTICULO NUMBER NOT NULL,
    NOMBRE             VARCHAR2(100) NOT NULL
);

ALTER TABLE C##EBAY.TBL_ESTADO_ARTICULO ADD CONSTRAINT ESTADO_ART_PK PRIMARY KEY (ID_ESTADO_ARTICULO);

CREATE TABLE C##EBAY.TBL_FAVORITOS (
    ID_FAVORITO    NUMBER NOT NULL,
    ID_VENTA       NUMBER NOT NULL,
    FECHA_GUARDADO DATE NOT NULL
);

ALTER TABLE C##EBAY.TBL_FAVORITOS ADD CONSTRAINT FAVORITOS_PK PRIMARY KEY (ID_FAVORITO, ID_VENTA);

CREATE TABLE C##EBAY.TBL_MENSAJES (
    ID_MENSAJE         NUMBER NOT NULL,
    ID_USUARIO_ORIGEN  NUMBER NOT NULL,
    ID_USUARIO_DESTINO NUMBER NOT NULL,
    FECHA_HORA         DATE,
    MENSAJE            VARCHAR2(4000)
);

ALTER TABLE C##EBAY.TBL_MENSAJES ADD CONSTRAINT MENSAJES_PK PRIMARY KEY (ID_MENSAJE);

CREATE TABLE C##EBAY.TBL_METODOS_PAGO (
    ID_METODO_PAGO      NUMBER NOT NULL,
    ID_TIPO_METODO_PAGO NUMBER NOT NULL,
    CUENTA              VARCHAR2(100) NOT NULL
);

ALTER TABLE C##EBAY.TBL_METODOS_PAGO ADD CONSTRAINT METODOS_PAGO_PK PRIMARY KEY (ID_METODO_PAGO);

CREATE TABLE C##EBAY.TBL_METODOS_PAGO_X_USUARIO (
    ID_USUARIO     NUMBER NOT NULL,
    ID_METODO_PAGO NUMBER NOT NULL
);

CREATE TABLE C##EBAY.TBL_PUJAS (
    ID_PUJA      NUMBER NOT NULL,
    ID_SUBASTA   NUMBER NOT NULL,
    ID_USUARIO   NUMBER NOT NULL,
    PUJA_USUARIO NUMBER NOT NULL,
    FECHA_PUJA   DATE NOT NULL
);

ALTER TABLE C##EBAY.TBL_PUJAS ADD CONSTRAINT PUJAS_PK PRIMARY KEY (ID_PUJA);

CREATE TABLE C##EBAY.TBL_PUTUACIONES (
    ID_PUNTUACION NUMBER NOT NULL,
    PUNTAJE       NUMBER NOT NULL,
    DESCRIPCION   VARCHAR2(255)
);

ALTER TABLE C##EBAY.TBL_PUTUACIONES ADD CONSTRAINT PUNTUACION_PK PRIMARY KEY (ID_PUNTUACION);

CREATE TABLE C##EBAY.TBL_SERVICIOS_ENVIO (
    ID_SERVICIO_ENVIO NUMBER NOT NULL,
    ID_ARTICULO       NUMBER NOT NULL,
    NOMBRE            VARCHAR2(100) NOT NULL,
    TIEMPO            NUMBER NOT NULL,
    COSTO             NUMBER NOT NULL
);

ALTER TABLE C##EBAY.TBL_SERVICIOS_ENVIO ADD CONSTRAINT SERV_ENVIO_PK PRIMARY KEY (ID_SERVICIO_ENVIO);

CREATE TABLE C##EBAY.TBL_SUBASTAS (
    ID_SUBASTA        NUMBER NOT NULL,
    ID_ARTICULO       NUMBER NOT NULL,
    PUJA_INICIAL      NUMBER NOT NULL,
    PRECIO            NUMBER,
    DURACION          NUMBER NOT NULL,
    FECHA_PUBLICACION DATE NOT NULL,
    CANTIDAD          NUMBER NOT NULL
);

ALTER TABLE C##EBAY.TBL_SUBASTAS ADD CONSTRAINT SUBASTAS_PK PRIMARY KEY (ID_SUBASTA);

CREATE TABLE C##EBAY.TBL_SUBASTAS_X_USUARIOS (
    ID_SUBASTA                    NUMBER NOT NULL,
    ID_USUARIO_EVALUADOR          NUMBER NOT NULL,
    ID_USUARIO_EVALUADO           NUMBER NOT NULL,
    DESCRIPCION_ARTICULO_RECIBIDO VARCHAR2(255) NOT NULL,
    PUNTAJE_DESCRIPCION_DADA      NUMBER,
    PUNTAJE_TIEMPO                NUMBER,
    PUNTAJE_COMUNICACION          NUMBER,
    FOTO                          BLOB,
    FECHA_VENTA                   DATE NOT NULL
);

CREATE TABLE C##EBAY.TBL_TIPO_CUENTA (
    ID_TIPO_CUENTA NUMBER NOT NULL,
    NOMBRE         VARCHAR2(100) NOT NULL
);

ALTER TABLE C##EBAY.TBL_TIPO_CUENTA ADD CONSTRAINT TIPO_CUENTA_PK PRIMARY KEY (ID_TIPO_CUENTA);

CREATE TABLE C##EBAY.TBL_TIPO_LUGAR (
    ID_TIPO_LUGAR NUMBER NOT NULL,
    NOMBRE        VARCHAR2(100) NOT NULL
);

ALTER TABLE C##EBAY.TBL_TIPO_LUGAR ADD CONSTRAINT TIPO_LUGAR_PK PRIMARY KEY (ID_TIPO_LUGAR);

CREATE TABLE C##EBAY.TBL_TIPO_METODOS_PAGO (
    ID_TIPO_METODO_PAGO NUMBER NOT NULL,
    NOMBRE              VARCHAR2(100) NOT NULL
);

ALTER TABLE C##EBAY.TBL_TIPO_METODOS_PAGO ADD CONSTRAINT TIPO_MET_PAGO_PK PRIMARY KEY (ID_TIPO_METODO_PAGO);

CREATE TABLE C##EBAY.TBL_USUARIOS (
    ID_USUARIO            NUMBER NOT NULL,
    ID_DIRECCION_PERSONAL NUMBER NOT NULL,
    ID_TIPO_CUENTA        NUMBER NOT NULL,
    ID_PUNTUACION_PERFIL  NUMBER NOT NULL,
    ID_CARRITO            NUMBER NOT NULL,
    ID_VENTA_CARRITO      NUMBER NOT NULL,
    ID_FAVORITO           NUMBER NOT NULL,
    ID_VENTA_FAVORITO     NUMBER NOT NULL,
    CORREO                VARCHAR2(100) NOT NULL,
    TELEFONO              VARCHAR2(100) NOT NULL,
    NOMBRE_USUARIO        VARCHAR2(100) NOT NULL,
    APELLIDO_USUARIO      VARCHAR2(100) NOT NULL,
    APODO                 VARCHAR2(100) NOT NULL,
    FECHA_REGISTRO        DATE NOT NULL,
    CONTRASENA            VARCHAR2(100) NOT NULL,
    DESCRIPCION           VARCHAR2(255),
    PRODUCTOS_VENDIDOS    NUMBER
);

ALTER TABLE C##EBAY.TBL_USUARIOS ADD CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_USUARIOS ADD CONSTRAINT USUARIO_CORREO_UN UNIQUE (CORREO);

ALTER TABLE C##EBAY.TBL_USUARIOS ADD CONSTRAINT USUARIO_TELEFONO_UN UNIQUE (TELEFONO);

ALTER TABLE C##EBAY.TBL_USUARIOS ADD CONSTRAINT USUARIO_CARRITO_UN UNIQUE (ID_CARRITO);

CREATE TABLE C##EBAY.TBL_VENTAS (
    ID_VENTA          NUMBER NOT NULL,
    ID_ARTICULO       NUMBER NOT NULL,
    PRECIO            NUMBER NOT NULL,
    PRECIO_MINIMO     NUMBER,
    FECHA_PUBLICACION DATE NOT NULL
);

ALTER TABLE C##EBAY.TBL_VENTAS ADD CONSTRAINT VENTAS_PK PRIMARY KEY (ID_VENTA);

CREATE TABLE C##EBAY.TBL_VENTAS_X_USUARIOS (
    ID_VENTA                      NUMBER NOT NULL,
    ID_USUARIO_EVALUADOR          NUMBER NOT NULL,
    ID_USUARIO_EVALUADO           NUMBER NOT NULL,
    DESCRIPCION_ARTICULO_RECIBIDO VARCHAR2(255) NOT NULL,
    PUNTAJE_DESCRIPCION_DADA      NUMBER,
    PUNTAJE_TIEMPO                NUMBER,
    PUNTAJE_COMUNICACION          NUMBER,
    FOTO                          BLOB,
    FECHA_VENTA                   DATE NOT NULL
);

-- Relaciones de claves foráneas
ALTER TABLE C##EBAY.TBL_ARTICULO
    ADD CONSTRAINT FK_ARTICULO_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
        REFERENCES C##EBAY.TBL_CATEGORIA (ID_CATEGORIA);

ALTER TABLE C##EBAY.TBL_ARTICULO
    ADD CONSTRAINT FK_ARTICULO_ESTADO FOREIGN KEY (ID_ESTADO_ARTICULO)
        REFERENCES C##EBAY.TBL_ESTADO_ARTICULO (ID_ESTADO_ARTICULO);

ALTER TABLE C##EBAY.TBL_ARTICULO
    ADD CONSTRAINT FK_ARTICULO_PUNTUACIONES FOREIGN KEY (ID_PUNTUACION_ARTICULO)
        REFERENCES C##EBAY.TBL_PUTUACIONES (ID_PUNTUACION);

ALTER TABLE C##EBAY.TBL_CARRITOS
    ADD CONSTRAINT FK_CARRITO_VENTAS FOREIGN KEY (ID_VENTA)
        REFERENCES C##EBAY.TBL_VENTAS (ID_VENTA);

ALTER TABLE C##EBAY.TBL_DIRECCIONES_ENVIO
    ADD CONSTRAINT FK_ENVIO_DIRECCION FOREIGN KEY (ID_DIRECCION)
        REFERENCES C##EBAY.TBL_DIRECCIONES (ID_DIRECCION);

ALTER TABLE C##EBAY.TBL_DIRECCIONES_ENVIO
    ADD CONSTRAINT FK_ENVIO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_DIRECCIONES_RECIBO
    ADD CONSTRAINT FK_RECIBO_DIRECCION FOREIGN KEY (ID_DIRECCION)
        REFERENCES C##EBAY.TBL_DIRECCIONES (ID_DIRECCION);

ALTER TABLE C##EBAY.TBL_DIRECCIONES_RECIBO
    ADD CONSTRAINT FK_RECIBO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_DIRECCIONES
    ADD CONSTRAINT FK_DIRECCION_SUPERIOR FOREIGN KEY (ID_DIRECCION_SUPERIOR)
        REFERENCES C##EBAY.TBL_DIRECCIONES (ID_DIRECCION);

ALTER TABLE C##EBAY.TBL_DIRECCIONES
    ADD CONSTRAINT FK_DIRECCION_TIPO FOREIGN KEY (ID_TIPO_LUGAR)
        REFERENCES C##EBAY.TBL_TIPO_LUGAR (ID_TIPO_LUGAR);

ALTER TABLE C##EBAY.TBL_FAVORITOS
    ADD CONSTRAINT FK_FAVORITO_VENTAS FOREIGN KEY (ID_VENTA)
        REFERENCES C##EBAY.TBL_VENTAS (ID_VENTA);

ALTER TABLE C##EBAY.TBL_MENSAJES
    ADD CONSTRAINT FK_MENSAJE_ORIGEN FOREIGN KEY (ID_USUARIO_ORIGEN)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_MENSAJES
    ADD CONSTRAINT FK_MENSAJE_DESTINO FOREIGN KEY (ID_USUARIO_DESTINO)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_METODOS_PAGO
    ADD CONSTRAINT FK_METODO_TIPO FOREIGN KEY (ID_TIPO_METODO_PAGO)
        REFERENCES C##EBAY.TBL_TIPO_METODOS_PAGO (ID_TIPO_METODO_PAGO);

ALTER TABLE C##EBAY.TBL_METODOS_PAGO_X_USUARIO
    ADD CONSTRAINT FK_PAGO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_METODOS_PAGO_X_USUARIO
    ADD CONSTRAINT FK_PAGO_METODO FOREIGN KEY (ID_METODO_PAGO)
        REFERENCES C##EBAY.TBL_METODOS_PAGO (ID_METODO_PAGO);

ALTER TABLE C##EBAY.TBL_PUJAS
    ADD CONSTRAINT FK_PUJA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_PUJAS
    ADD CONSTRAINT FK_PUJA_SUBASTA FOREIGN KEY (ID_SUBASTA)
        REFERENCES C##EBAY.TBL_SUBASTAS (ID_SUBASTA);

ALTER TABLE C##EBAY.TBL_SERVICIOS_ENVIO
    ADD CONSTRAINT FK_SERV_ENVIO_ARTICULO FOREIGN KEY (ID_ARTICULO)
        REFERENCES C##EBAY.TBL_ARTICULO (ID_ARTICULO);

ALTER TABLE C##EBAY.TBL_SUBASTAS
    ADD CONSTRAINT FK_SUBASTA_ARTICULO FOREIGN KEY (ID_ARTICULO)
        REFERENCES C##EBAY.TBL_ARTICULO (ID_ARTICULO);

ALTER TABLE C##EBAY.TBL_SUBASTAS_X_USUARIOS
    ADD CONSTRAINT FK_SUBASTA_USUARIO_EV FOREIGN KEY (ID_USUARIO_EVALUADOR)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_SUBASTAS_X_USUARIOS
    ADD CONSTRAINT FK_SUBASTA_USUARIO_EVAL FOREIGN KEY (ID_USUARIO_EVALUADO)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_SUBASTAS_X_USUARIOS
    ADD CONSTRAINT FK_SUBASTA_VENTA FOREIGN KEY (ID_SUBASTA)
        REFERENCES C##EBAY.TBL_SUBASTAS (ID_SUBASTA);

ALTER TABLE C##EBAY.TBL_USUARIOS
    ADD CONSTRAINT FK_USUARIO_DIRECCION FOREIGN KEY (ID_DIRECCION_PERSONAL)
        REFERENCES C##EBAY.TBL_DIRECCIONES (ID_DIRECCION);

ALTER TABLE C##EBAY.TBL_USUARIOS
    ADD CONSTRAINT FK_USUARIO_TIPO_CUENTA FOREIGN KEY (ID_TIPO_CUENTA)
        REFERENCES C##EBAY.TBL_TIPO_CUENTA (ID_TIPO_CUENTA);

ALTER TABLE C##EBAY.TBL_USUARIOS
    ADD CONSTRAINT FK_USUARIO_CARRITO FOREIGN KEY (ID_CARRITO, ID_VENTA_CARRITO)
        REFERENCES C##EBAY.TBL_CARRITOS (ID_CARRITO, ID_VENTA);

ALTER TABLE C##EBAY.TBL_USUARIOS
    ADD CONSTRAINT FK_USUARIO_FAVORITO FOREIGN KEY (ID_FAVORITO, ID_VENTA_FAVORITO)
        REFERENCES C##EBAY.TBL_FAVORITOS (ID_FAVORITO, ID_VENTA);

ALTER TABLE C##EBAY.TBL_USUARIOS
    ADD CONSTRAINT FK_USUARIO_PUNTUACION FOREIGN KEY (ID_PUNTUACION_PERFIL)
        REFERENCES C##EBAY.TBL_PUTUACIONES (ID_PUNTUACION);

ALTER TABLE C##EBAY.TBL_VENTAS
    ADD CONSTRAINT FK_VENTA_ARTICULO FOREIGN KEY (ID_ARTICULO)
        REFERENCES C##EBAY.TBL_ARTICULO (ID_ARTICULO);

ALTER TABLE C##EBAY.TBL_VENTAS_X_USUARIOS
    ADD CONSTRAINT FK_VENTA_USUARIO_EV FOREIGN KEY (ID_USUARIO_EVALUADOR)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_VENTAS_X_USUARIOS
    ADD CONSTRAINT FK_VENTA_USUARIO_EVAL FOREIGN KEY (ID_USUARIO_EVALUADO)
        REFERENCES C##EBAY.TBL_USUARIOS (ID_USUARIO);

ALTER TABLE C##EBAY.TBL_VENTAS_X_USUARIOS
    ADD CONSTRAINT FK_VENTA_VENTAS FOREIGN KEY (ID_VENTA)
        REFERENCES C##EBAY.TBL_VENTAS (ID_VENTA);



