SET DEFINE OFF;

-- 1. Insertar datos en las tablas de catálogos o lookup tables (Tablas padres)

-- Tabla TBL_CATEGORIA
INSERT INTO C##EBAY.TBL_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (1, 'Electrónica', 'Dispositivos electrónicos y accesorios');
INSERT INTO C##EBAY.TBL_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (2, 'Hogar', 'Artículos para el hogar');
INSERT INTO C##EBAY.TBL_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (3, 'Moda', 'Ropa y accesorios');
INSERT INTO C##EBAY.TBL_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (4, 'Deportes', 'Equipamiento y ropa deportiva');
INSERT INTO C##EBAY.TBL_CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (5, 'Libros', 'Libros y material de lectura');

-- Tabla TBL_ESTADO_ARTICULO
INSERT INTO C##EBAY.TBL_ESTADO_ARTICULO (ID_ESTADO_ARTICULO, NOMBRE) VALUES (1, 'Nuevo');
INSERT INTO C##EBAY.TBL_ESTADO_ARTICULO (ID_ESTADO_ARTICULO, NOMBRE) VALUES (2, 'Usado - Como Nuevo');
INSERT INTO C##EBAY.TBL_ESTADO_ARTICULO (ID_ESTADO_ARTICULO, NOMBRE) VALUES (3, 'Usado - Bueno');
INSERT INTO C##EBAY.TBL_ESTADO_ARTICULO (ID_ESTADO_ARTICULO, NOMBRE) VALUES (4, 'Usado - Aceptable');
INSERT INTO C##EBAY.TBL_ESTADO_ARTICULO (ID_ESTADO_ARTICULO, NOMBRE) VALUES (5, 'Para Repuestos');

-- Tabla TBL_PUNTUACIONES
INSERT INTO C##EBAY.TBL_PUNTUACIONES (ID_PUNTUACION, PUNTAJE, DESCRIPCION) VALUES (1, 5, 'Excelente');
INSERT INTO C##EBAY.TBL_PUNTUACIONES (ID_PUNTUACION, PUNTAJE, DESCRIPCION) VALUES (2, 4, 'Muy Bueno');
INSERT INTO C##EBAY.TBL_PUNTUACIONES (ID_PUNTUACION, PUNTAJE, DESCRIPCION) VALUES (3, 3, 'Bueno');
INSERT INTO C##EBAY.TBL_PUNTUACIONES (ID_PUNTUACION, PUNTAJE, DESCRIPCION) VALUES (4, 2, 'Regular');
INSERT INTO C##EBAY.TBL_PUNTUACIONES (ID_PUNTUACION, PUNTAJE, DESCRIPCION) VALUES (5, 1, 'Malo');

-- Tabla TBL_TIPO_CUENTA
INSERT INTO C##EBAY.TBL_TIPO_CUENTA (ID_TIPO_CUENTA, NOMBRE) VALUES (1, 'Comprador');
INSERT INTO C##EBAY.TBL_TIPO_CUENTA (ID_TIPO_CUENTA, NOMBRE) VALUES (2, 'Vendedor');
INSERT INTO C##EBAY.TBL_TIPO_CUENTA (ID_TIPO_CUENTA, NOMBRE) VALUES (3, 'Administrador');

-- Tabla TBL_TIPO_LUGAR
INSERT INTO C##EBAY.TBL_TIPO_LUGAR (ID_TIPO_LUGAR, NOMBRE) VALUES (1, 'Calle');
INSERT INTO C##EBAY.TBL_TIPO_LUGAR (ID_TIPO_LUGAR, NOMBRE) VALUES (2, 'Colonia');
INSERT INTO C##EBAY.TBL_TIPO_LUGAR (ID_TIPO_LUGAR, NOMBRE) VALUES (3, 'Avenida');
INSERT INTO C##EBAY.TBL_TIPO_LUGAR (ID_TIPO_LUGAR, NOMBRE) VALUES (4, 'Boulevard');

-- Tabla TBL_TIPO_METODOS_PAGO
INSERT INTO C##EBAY.TBL_TIPO_METODOS_PAGO (ID_TIPO_METODO_PAGO, NOMBRE) VALUES (1, 'Tarjeta de Crédito');
INSERT INTO C##EBAY.TBL_TIPO_METODOS_PAGO (ID_TIPO_METODO_PAGO, NOMBRE) VALUES (2, 'Tarjeta de Débito');
INSERT INTO C##EBAY.TBL_TIPO_METODOS_PAGO (ID_TIPO_METODO_PAGO, NOMBRE) VALUES (3, 'PayPal');

-- 2. Insertar datos en las tablas principales (Tablas que dependen de catálogos)

-- Tabla TBL_DIRECCIONES
INSERT INTO C##EBAY.TBL_DIRECCIONES (ID_DIRECCION, ID_DIRECCION_SUPERIOR, ID_TIPO_LUGAR, NOMBRE, LONGITUD, LATITUD) 
VALUES (1, 1, 1, 'Calle 123', '-99.1234', '19.4321');
INSERT INTO C##EBAY.TBL_DIRECCIONES (ID_DIRECCION, ID_DIRECCION_SUPERIOR, ID_TIPO_LUGAR, NOMBRE, LONGITUD, LATITUD) 
VALUES (2, 1, 2, 'Colonia ABC', '-99.5678', '19.8765');
INSERT INTO C##EBAY.TBL_DIRECCIONES (ID_DIRECCION, ID_DIRECCION_SUPERIOR, ID_TIPO_LUGAR, NOMBRE, LONGITUD, LATITUD) 
VALUES (3, 1, 1, 'Avenida 456', '-98.1234', '18.4321');
INSERT INTO C##EBAY.TBL_DIRECCIONES (ID_DIRECCION, ID_DIRECCION_SUPERIOR, ID_TIPO_LUGAR, NOMBRE, LONGITUD, LATITUD) 
VALUES (4, 3, 2, 'Barrio XYZ', '-98.5678', '18.8765');
INSERT INTO C##EBAY.TBL_DIRECCIONES (ID_DIRECCION, ID_DIRECCION_SUPERIOR, ID_TIPO_LUGAR, NOMBRE, LONGITUD, LATITUD) 
VALUES (5, 1, 1, 'Boulevard 789', '-97.1234', '17.4321');

-- Tabla TBL_USUARIOS
INSERT INTO C##EBAY.TBL_USUARIOS (ID_USUARIO, ID_DIRECCION_PERSONAL, ID_TIPO_CUENTA, ID_PUNTUACION_PERFIL, ID_CARRITO, ID_VENTA_CARRITO, ID_FAVORITO, ID_VENTA_FAVORITO, CORREO, TELEFONO, NOMBRE_USUARIO, APELLIDO_USUARIO, APODO, FECHA_REGISTRO, CONTRASENA, DESCRIPCION, PRODUCTOS_VENDIDOS) 
VALUES (1, 1, 1, 1, 1, 1, 1, 1, 'usuario1@example.com', '1234567890', 'Juan', 'Pérez', 'Juanito', SYSDATE, 'password123', 'Usuario activo en la plataforma', 10);
INSERT INTO C##EBAY.TBL_USUARIOS (ID_USUARIO, ID_DIRECCION_PERSONAL, ID_TIPO_CUENTA, ID_PUNTUACION_PERFIL, ID_CARRITO, ID_VENTA_CARRITO, ID_FAVORITO, ID_VENTA_FAVORITO, CORREO, TELEFONO, NOMBRE_USUARIO, APELLIDO_USUARIO, APODO, FECHA_REGISTRO, CONTRASENA, DESCRIPCION, PRODUCTOS_VENDIDOS) 
VALUES (2, 2, 1, 2, 2, 1, 1, 1, 'usuario2@example.com', '0987654321', 'María', 'López', 'Marita', SYSDATE, 'password456', 'Compradora frecuente', 5);
INSERT INTO C##EBAY.TBL_USUARIOS (ID_USUARIO, ID_DIRECCION_PERSONAL, ID_TIPO_CUENTA, ID_PUNTUACION_PERFIL, ID_CARRITO, ID_VENTA_CARRITO, ID_FAVORITO, ID_VENTA_FAVORITO, CORREO, TELEFONO, NOMBRE_USUARIO, APELLIDO_USUARIO, APODO, FECHA_REGISTRO, CONTRASENA, DESCRIPCION, PRODUCTOS_VENDIDOS) 
VALUES (3, 3, 2, 3, 3, 1, 1, 1, 'usuario3@example.com', '1122334455', 'Carlos', 'García', 'Carlitos', SYSDATE, 'password789', 'Vendedor ocasional', 2);
INSERT INTO C##EBAY.TBL_USUARIOS (ID_USUARIO, ID_DIRECCION_PERSONAL, ID_TIPO_CUENTA, ID_PUNTUACION_PERFIL, ID_CARRITO, ID_VENTA_CARRITO, ID_FAVORITO, ID_VENTA_FAVORITO, CORREO, TELEFONO, NOMBRE_USUARIO, APELLIDO_USUARIO, APODO, FECHA_REGISTRO, CONTRASENA, DESCRIPCION, PRODUCTOS_VENDIDOS) 
VALUES (4, 4, 2, 4, 4, 1, 1, 1, 'usuario4@example.com', '6677889900', 'Laura', 'Martínez', 'Laurita', SYSDATE, 'password101112', 'Compradora y vendedora activa', 7);
INSERT INTO C##EBAY.TBL_USUARIOS (ID_USUARIO, ID_DIRECCION_PERSONAL, ID_TIPO_CUENTA, ID_PUNTUACION_PERFIL, ID_CARRITO, ID_VENTA_CARRITO, ID_FAVORITO, ID_VENTA_FAVORITO, CORREO, TELEFONO, NOMBRE_USUARIO, APELLIDO_USUARIO, APODO, FECHA_REGISTRO, CONTRASENA, DESCRIPCION, PRODUCTOS_VENDIDOS) 
VALUES (5, 5, 1, 5, 5, 1, 1, 1, 'usuario5@example.com', '5544332211', 'Ana', 'Gómez', 'Anita', SYSDATE, 'password131415', 'Usuario nuevo', 1);

-- 3. Insertar datos en las tablas que dependen de usuarios y artículos

-- Tabla TBL_ARTICULO
INSERT INTO C##EBAY.TBL_ARTICULO (ID_ARTICULO, ID_CATEGORIA, ID_ESTADO_ARTICULO, ID_PUNTUACION_ARTICULO, NOMBRE, TITULO, DESCRIPCION, MARCA, MODELO, IMAGEN) 
VALUES (1, 1, 1, 1, 'iPhone 13', 'iPhone 13 128GB', 'iPhone 13 con 128GB de almacenamiento', 'Apple', 'A2633', EMPTY_BLOB());
INSERT INTO C##EBAY.TBL_ARTICULO (ID_ARTICULO, ID_CATEGORIA, ID_ESTADO_ARTICULO, ID_PUNTUACION_ARTICULO, NOMBRE, TITULO, DESCRIPCION, MARCA, MODELO, IMAGEN) 
VALUES (2, 2, 2, 2, 'Sofá', 'Sofá de 3 plazas', 'Sofá cómodo de 3 plazas en color gris', 'Ikea', 'Klippan', EMPTY_BLOB());
INSERT INTO C##EBAY.TBL_ARTICULO (ID_ARTICULO, ID_CATEGORIA, ID_ESTADO_ARTICULO, ID_PUNTUACION_ARTICULO, NOMBRE, TITULO, DESCRIPCION, MARCA, MODELO, IMAGEN) 
VALUES (3, 3, 3, 3, 'Chaqueta de cuero', 'Chaqueta de cuero negra', 'Chaqueta de cuero para moto, talla M', 'Zara', 'Moto Jacket', EMPTY_BLOB());
INSERT INTO C##EBAY.TBL_ARTICULO (ID_ARTICULO, ID_CATEGORIA, ID_ESTADO_ARTICULO, ID_PUNTUACION_ARTICULO, NOMBRE, TITULO, DESCRIPCION, MARCA, MODELO, IMAGEN) 
VALUES (4, 4, 1, 4, 'Bicicleta', 'Bicicleta de montaña', 'Bicicleta de montaña con 21 velocidades', 'Trek', 'Marlin 5', EMPTY_BLOB());
INSERT INTO C##EBAY.TBL_ARTICULO (ID_ARTICULO, ID_CATEGORIA, ID_ESTADO_ARTICULO, ID_PUNTUACION_ARTICULO, NOMBRE, TITULO, DESCRIPCION, MARCA, MODELO, IMAGEN) 
VALUES (5, 5, 5, 5, 'Libro', '1984 de George Orwell', 'Edición especial de 1984 con tapa dura', 'Editorial XYZ', '1984', EMPTY_BLOB());

-- Tabla TBL_VENTAS
INSERT INTO C##EBAY.TBL_VENTAS (ID_VENTA, ID_ARTICULO, PRECIO, PRECIO_MINIMO, FECHA_PUBLICACION) 
VALUES (1, 1, 900.00, 850.00, SYSDATE);
INSERT INTO C##EBAY.TBL_VENTAS (ID_VENTA, ID_ARTICULO, PRECIO, PRECIO_MINIMO, FECHA_PUBLICACION) 
VALUES (2, 2, 200.00, 180.00, SYSDATE - 1);
INSERT INTO C##EBAY.TBL_VENTAS (ID_VENTA, ID_ARTICULO, PRECIO, PRECIO_MINIMO, FECHA_PUBLICACION) 
VALUES (3, 3, 100.00, 90.00, SYSDATE - 2);
INSERT INTO C##EBAY.TBL_VENTAS (ID_VENTA, ID_ARTICULO, PRECIO, PRECIO_MINIMO, FECHA_PUBLICACION) 
VALUES (4, 4, 300.00, 280.00, SYSDATE - 3);
INSERT INTO C##EBAY.TBL_VENTAS (ID_VENTA, ID_ARTICULO, PRECIO, PRECIO_MINIMO, FECHA_PUBLICACION) 
VALUES (5, 5, 20.00, 15.00, SYSDATE - 4);

-- Tabla TBL_CARRITOS
INSERT INTO C##EBAY.TBL_CARRITOS (ID_CARRITO, ID_VENTA, CANTIDAD) 
VALUES (1, 1, 1);
INSERT INTO C##EBAY.TBL_CARRITOS (ID_CARRITO, ID_VENTA, CANTIDAD) 
VALUES (2, 2, 2);
INSERT INTO C##EBAY.TBL_CARRITOS (ID_CARRITO, ID_VENTA, CANTIDAD) 
VALUES (3, 3, 1);
INSERT INTO C##EBAY.TBL_CARRITOS (ID_CARRITO, ID_VENTA, CANTIDAD) 
VALUES (4, 4, 3);
INSERT INTO C##EBAY.TBL_CARRITOS (ID_CARRITO, ID_VENTA, CANTIDAD) 
VALUES (5, 5, 1);

-- Tabla TBL_FAVORITOS
INSERT INTO C##EBAY.TBL_FAVORITOS (ID_FAVORITO, ID_VENTA, FECHA_GUARDADO) 
VALUES (1, 1, SYSDATE);
INSERT INTO C##EBAY.TBL_FAVORITOS (ID_FAVORITO, ID_VENTA, FECHA_GUARDADO) 
VALUES (2, 2, SYSDATE - 1);
INSERT INTO C##EBAY.TBL_FAVORITOS (ID_FAVORITO, ID_VENTA, FECHA_GUARDADO) 
VALUES (3, 3, SYSDATE - 2);
INSERT INTO C##EBAY.TBL_FAVORITOS (ID_FAVORITO, ID_VENTA, FECHA_GUARDADO) 
VALUES (4, 4, SYSDATE - 3);
INSERT INTO C##EBAY.TBL_FAVORITOS (ID_FAVORITO, ID_VENTA, FECHA_GUARDADO) 
VALUES (5, 5, SYSDATE - 4);

-- Tabla TBL_SUBASTAS
INSERT INTO C##EBAY.TBL_SUBASTAS (ID_SUBASTA, ID_ARTICULO, PUJA_INICIAL, PRECIO, DURACION, FECHA_PUBLICACION, CANTIDAD) 
VALUES (1, 1, 800.00, 1, 7, SYSDATE, 1);
INSERT INTO C##EBAY.TBL_SUBASTAS (ID_SUBASTA, ID_ARTICULO, PUJA_INICIAL, PRECIO, DURACION, FECHA_PUBLICACION, CANTIDAD) 
VALUES (2, 2, 150.00, 1, 5, SYSDATE - 1, 1);
INSERT INTO C##EBAY.TBL_SUBASTAS (ID_SUBASTA, ID_ARTICULO, PUJA_INICIAL, PRECIO, DURACION, FECHA_PUBLICACION, CANTIDAD) 
VALUES (3, 3, 75.00, 1, 3, SYSDATE - 2, 1);
INSERT INTO C##EBAY.TBL_SUBASTAS (ID_SUBASTA, ID_ARTICULO, PUJA_INICIAL, PRECIO, DURACION, FECHA_PUBLICACION, CANTIDAD) 
VALUES (4, 4, 250.00, 1, 10, SYSDATE - 3, 1);
INSERT INTO C##EBAY.TBL_SUBASTAS (ID_SUBASTA, ID_ARTICULO, PUJA_INICIAL, PRECIO, DURACION, FECHA_PUBLICACION, CANTIDAD) 
VALUES (5, 5, 10.00, 1, 2, SYSDATE - 4, 1);

-- Tabla TBL_PUJAS
INSERT INTO C##EBAY.TBL_PUJAS (ID_PUJA, ID_SUBASTA, ID_USUARIO, PUJA_USUARIO, FECHA_PUJA) 
VALUES (1, 1, 1, 850.00, SYSDATE);
INSERT INTO C##EBAY.TBL_PUJAS (ID_PUJA, ID_SUBASTA, ID_USUARIO, PUJA_USUARIO, FECHA_PUJA) 
VALUES (2, 2, 2, 160.00, SYSDATE - 1);
INSERT INTO C##EBAY.TBL_PUJAS (ID_PUJA, ID_SUBASTA, ID_USUARIO, PUJA_USUARIO, FECHA_PUJA) 
VALUES (3, 3, 3, 80.00, SYSDATE - 2);
INSERT INTO C##EBAY.TBL_PUJAS (ID_PUJA, ID_SUBASTA, ID_USUARIO, PUJA_USUARIO, FECHA_PUJA) 
VALUES (4, 4, 4, 260.00, SYSDATE - 3);
INSERT INTO C##EBAY.TBL_PUJAS (ID_PUJA, ID_SUBASTA, ID_USUARIO, PUJA_USUARIO, FECHA_PUJA) 
VALUES (5, 5, 5, 12.00, SYSDATE - 4);

-- Tabla TBL_METODOS_PAGO
INSERT INTO C##EBAY.TBL_METODOS_PAGO (ID_METODO_PAGO, ID_TIPO_METODO_PAGO, CUENTA) 
VALUES (1, 1, '1234-5678-9012-3456');
INSERT INTO C##EBAY.TBL_METODOS_PAGO (ID_METODO_PAGO, ID_TIPO_METODO_PAGO, CUENTA) 
VALUES (2, 2, '9876-5432-1098-7654');
INSERT INTO C##EBAY.TBL_METODOS_PAGO (ID_METODO_PAGO, ID_TIPO_METODO_PAGO, CUENTA) 
VALUES (3, 3, '5566-7788-9900-1122');
INSERT INTO C##EBAY.TBL_METODOS_PAGO (ID_METODO_PAGO, ID_TIPO_METODO_PAGO, CUENTA) 
VALUES (4, 1, '6655-4433-2211-0099');
INSERT INTO C##EBAY.TBL_METODOS_PAGO (ID_METODO_PAGO, ID_TIPO_METODO_PAGO, CUENTA) 
VALUES (5, 2, '8899-7766-5544-3322');

-- Tabla TBL_METODOS_PAGO_X_USUARIO
INSERT INTO C##EBAY.TBL_METODOS_PAGO_X_USUARIO (ID_USUARIO, ID_METODO_PAGO) 
VALUES (1, 1);
INSERT INTO C##EBAY.TBL_METODOS_PAGO_X_USUARIO (ID_USUARIO, ID_METODO_PAGO) 
VALUES (2, 2);
INSERT INTO C##EBAY.TBL_METODOS_PAGO_X_USUARIO (ID_USUARIO, ID_METODO_PAGO) 
VALUES (3, 3);
INSERT INTO C##EBAY.TBL_METODOS_PAGO_X_USUARIO (ID_USUARIO, ID_METODO_PAGO) 
VALUES (4, 4);
INSERT INTO C##EBAY.TBL_METODOS_PAGO_X_USUARIO (ID_USUARIO, ID_METODO_PAGO) 
VALUES (5, 5);

-- Tabla TBL_DIRECCIONES_ENVIO
INSERT INTO C##EBAY.TBL_DIRECCIONES_ENVIO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (1, 1, 'A', '-99.1234', '19.4321');
INSERT INTO C##EBAY.TBL_DIRECCIONES_ENVIO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (2, 2, 'B', '-99.5678', '19.8765');
INSERT INTO C##EBAY.TBL_DIRECCIONES_ENVIO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (3, 3, 'A', '-98.1234', '18.4321');
INSERT INTO C##EBAY.TBL_DIRECCIONES_ENVIO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (4, 4, 'B', '-98.5678', '18.8765');
INSERT INTO C##EBAY.TBL_DIRECCIONES_ENVIO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (5, 5, 'A', '-97.1234', '17.4321');

-- Tabla TBL_DIRECCIONES_RECIBO
INSERT INTO C##EBAY.TBL_DIRECCIONES_RECIBO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (1, 1, 'A', '-99.1234', '19.4321');
INSERT INTO C##EBAY.TBL_DIRECCIONES_RECIBO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (2, 2, 'B', '-99.5678', '19.8765');
INSERT INTO C##EBAY.TBL_DIRECCIONES_RECIBO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (3, 3, 'A', '-98.1234', '18.4321');
INSERT INTO C##EBAY.TBL_DIRECCIONES_RECIBO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (4, 4, 'B', '-98.5678', '18.8765');
INSERT INTO C##EBAY.TBL_DIRECCIONES_RECIBO (ID_USUARIO, ID_DIRECCION, PRIORIDAD, LONGITUD, LATITUD) 
VALUES (5, 5, 'A', '-97.1234', '17.4321');

-- Tabla TBL_SERVICIOS_ENVIO
INSERT INTO C##EBAY.TBL_SERVICIOS_ENVIO (ID_SERVICIO_ENVIO, ID_ARTICULO, NOMBRE, TIEMPO, COSTO) 
VALUES (1, 1, 'Envío Express', 2, 50.00);
INSERT INTO C##EBAY.TBL_SERVICIOS_ENVIO (ID_SERVICIO_ENVIO, ID_ARTICULO, NOMBRE, TIEMPO, COSTO) 
VALUES (2, 2, 'Envío Estándar', 5, 30.00);
INSERT INTO C##EBAY.TBL_SERVICIOS_ENVIO (ID_SERVICIO_ENVIO, ID_ARTICULO, NOMBRE, TIEMPO, COSTO) 
VALUES (3, 3, 'Envío Internacional', 10, 100.00);
INSERT INTO C##EBAY.TBL_SERVICIOS_ENVIO (ID_SERVICIO_ENVIO, ID_ARTICULO, NOMBRE, TIEMPO, COSTO) 
VALUES (4, 4, 'Envío Gratuito', 7, 0.00);
INSERT INTO C##EBAY.TBL_SERVICIOS_ENVIO (ID_SERVICIO_ENVIO, ID_ARTICULO, NOMBRE, TIEMPO, COSTO) 
VALUES (5, 5, 'Recogida en Tienda', 1, 0.00);

-- Tabla TBL_MENSAJES
INSERT INTO C##EBAY.TBL_MENSAJES (ID_MENSAJE, ID_USUARIO_ORIGEN, ID_USUARIO_DESTINO, FECHA_HORA, MENSAJE) 
VALUES (1, 1, 2, SYSDATE, 'Hola, estoy interesado en tu artículo.');
INSERT INTO C##EBAY.TBL_MENSAJES (ID_MENSAJE, ID_USUARIO_ORIGEN, ID_USUARIO_DESTINO, FECHA_HORA, MENSAJE) 
VALUES (2, 2, 3, SYSDATE - 1, '¿Puedes bajar el precio?');
INSERT INTO C##EBAY.TBL_MENSAJES (ID_MENSAJE, ID_USUARIO_ORIGEN, ID_USUARIO_DESTINO, FECHA_HORA, MENSAJE) 
VALUES (3, 3, 4, SYSDATE - 2, '¿Aceptas cambios?');
INSERT INTO C##EBAY.TBL_MENSAJES (ID_MENSAJE, ID_USUARIO_ORIGEN, ID_USUARIO_DESTINO, FECHA_HORA, MENSAJE) 
VALUES (4, 4, 5, SYSDATE - 3, 'Gracias por la compra.');
INSERT INTO C##EBAY.TBL_MENSAJES (ID_MENSAJE, ID_USUARIO_ORIGEN, ID_USUARIO_DESTINO, FECHA_HORA, MENSAJE) 
VALUES (5, 5, 1, SYSDATE - 4, '¡Artículo recibido en perfectas condiciones!');

COMMIT;
