-- Crear el usuario
CREATE USER C##EBAY IDENTIFIED BY ebay
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

--permisos básicos al usuario
GRANT CONNECT, RESOURCE TO C##EBAY;

--permisos adicionales si es necesario
GRANT CREATE SESSION TO C##EBAY;
GRANT CREATE TABLE TO C##EBAY;
GRANT CREATE VIEW TO C##EBAY;
GRANT CREATE PROCEDURE TO C##EBAY;
GRANT CREATE SEQUENCE TO C##EBAY;
GRANT CREATE TRIGGER TO C##EBAY;
GRANT CREATE SYNONYM TO C##EBAY;
GRANT CREATE ANY INDEX TO C##EBAY;
GRANT UNLIMITED TABLESPACE TO C##EBAY;

--permisos para crear y administrar tablas y sus objetos asociados
GRANT CREATE ANY TABLE TO C##EBAY;
GRANT ALTER ANY TABLE TO C##EBAY;
GRANT DROP ANY TABLE TO C##EBAY;
GRANT INSERT ANY TABLE TO C##EBAY;
GRANT UPDATE ANY TABLE TO C##EBAY;
GRANT DELETE ANY TABLE TO C##EBAY;
GRANT SELECT ANY TABLE TO C##EBAY;

--permisos para trabajar con secuencias
GRANT CREATE ANY SEQUENCE TO C##EBAY;
GRANT ALTER ANY SEQUENCE TO C##EBAY;
GRANT DROP ANY SEQUENCE TO C##EBAY;

--permisos para trabajar con triggers
GRANT CREATE ANY TRIGGER TO C##EBAY;
GRANT ALTER ANY TRIGGER TO C##EBAY;
GRANT DROP ANY TRIGGER TO C##EBAY;

--permisos para trabajar con procedimientos almacenados
GRANT CREATE ANY PROCEDURE TO C##EBAY;
GRANT ALTER ANY PROCEDURE TO C##EBAY;
GRANT DROP ANY PROCEDURE TO C##EBAY;

--permisos para trabajar con vistas
GRANT CREATE ANY VIEW TO C##EBAY;
GRANT DROP ANY VIEW TO C##EBAY;

--permisos para trabajar con sinónimos
GRANT CREATE ANY SYNONYM TO C##EBAY;
GRANT DROP ANY SYNONYM TO C##EBAY;

--permisos para trabajar con índices
GRANT CREATE ANY INDEX TO C##EBAY;
GRANT ALTER ANY INDEX TO C##EBAY;
GRANT DROP ANY INDEX TO C##EBAY;

--DROP USER C##EBAY CASCADE;